### ISSUE TITLE
Search engine gets removed on `shutdown` when not set default.

### ISSUE THREAD

**Issue by mrshu** [mozilla/example-search-addon#1]
We use the `SearchSetting` in the [firefox-zeroclick](https://github.com/duckduckgo/firefox-zeroclickinfo) extension to add DuckDuckGo as a search engine and set it as default on install. 

That works quite well. However, when the user changes the default search engine by setting some other in the popup list on the top right DuckDuckGo is removed on the next `shutdown` and it is not available in the list of the search engines.

If the extension tries to install the search engine without setting it as default by running the following

```
SearchSettings.addSearchEngine(ENGINE_URL, false);
```

it does add DuckDuckGo into the list but also makes it default.

Is this the intended behaviour? Are we doing something wrong?

This annoys many people and so we'd like fix it.

Thanks a lot.

**Comment by kmaglione** [comment]
`addSearchEngine` needs to be called on every run. The second argument should have no bearing on whether the search engine is selected on subsequent calls. It should only ever be selected the first time the engine is created. A change introduced in Firefox 23 seems to have caused it to be selected on every call, though.

**Comment by mrshu** [comment]
@kmaglione thanks for looking into this.

However, when I used your fixed library it only worked in this scenario:

1) Install the addon (https://github.com/duckduckgo/firefox-zeroclickinfo/blob/master/build/ddg_for_firefox.xpi?raw=true)
2) Choose a different search engine than DuckDuckGo and restart Firefox.
3) On another start of Firefox you'll see that DuckDuckGo is the default again. Once again choose a different search engine and restart Firefox.
4) On the next start the default search engine will finally be the one you selected.

Is this a problem of the extension? Is there something wrong with the usage of the library? The code is available [here](https://github.com/duckduckgo/firefox-zeroclickinfo/blob/master/lib/main.js#L634) -- is there something obviously wrong with it? This issue is quite nasty for us because it looks like DuckDuckGo is trying to be set at default at all times even though that was never our intention.

Thanks again for looking into it.
